export const SET_BOOK_SEARCH_SEARCHED = 'SET_BOOK_SEARCH_SEARCHED'
export const SET_BOOK_SEARCH_NAME = 'SET_BOOK_SEARCH_NAME'
export const SET_BOOK_SEARCH_ISSUE_YEAR_GT = 'SET_BOOK_SEARCH_ISSUE_YEAR_GT'
export const SET_BOOK_SEARCH_ISSUE_YEAR_LT = 'SET_BOOK_SEARCH_ISSUE_YEAR_LT'
export const SET_BOOK_SEARCH_BOOK_COUNT = 'SET_BOOK_SEARCH_BOOK_COUNT'
export const SET_BOOK_SEARCH_PAGE_SIZE = 'SET_BOOK_SEARCH_PAGE_SIZE'
export const SET_BOOK_SEARCH_PAGE_COUNT_GT = 'SET_BOOK_SEARCH_PAGE_COUNT_GT'
export const SET_BOOK_SEARCH_PAGE_COUNT_LT = 'SET_BOOK_SEARCH_PAGE_COUNT_LT'
export const SET_BOOK_SEARCH_ERROR = 'SET_BOOK_SEARCH_ERROR'
export const SET_BOOK_SEARCH_AUTHOR_ID = 'SET_BOOK_SEARCH_AUTHOR_ID'
export const SET_BOOK_SEARCH_PAGE = 'SET_BOOK_SEARCH_PAGE'

export const SET_BOOK_SEARCH_AUTHORS = 'SET_AUTHORS'
export const SET_BOOKS = 'SET_BOOKS'

export const START_BOOKS_LOADING = 'START_BOOK_LOADING'
export const FINISH_BOOKS_LOADING = 'FINISH_BOOK_LOADING'

//Модальное окно подтверждения удаления
export const SHOW_DELETE_CONFIRM_MODAL = 'SHOW_DELETE_CONFIRM_MODAL'
export const HIDE_DELETE_CONFIRM_MODAL = 'HIDE_DELETE_CONFIRM_MODAL'
export const SET_DELETE_CONFIRM_TEXT = 'SET_DELETE_CONFIRM_TEXT'

//Уведомления
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION'
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'